---
- name: Install the board version of the liquid toolkit in chroot
  hosts: image
  vars_files:
    - ['vars/defaults.yml', 'vars/config.yml']
  roles:
    - common
    - devel
    - liquid-core
    - hotspot
